language: node_js
node_js: stable
dist: trusty
sudo: required
group: edge
env:
  global:
  - secure: bIEoWz3T6AStfFfETTWQWYaAfcpWMqAtnblXQpRLUoHzSruRpr9wCUHPUMLVenudSUih3P6I2Kz6oiYvLF6ipATwn30d1mTmr6PdVCIcLAD5dFTSJqCYeZtZ2qW+NQxUSfxxyp+r36L1QlExTVtu2uLa2faZYymP+xEfaYxt/0CtiX4lQGW+JSa6or/HDFC5yIMmE9YF7o3nFAuz33QsQautf0kRgISAMKvqlHbGJ9WRH+GkjgByKc1SGGL39cI9dMwLZYT+NYtRKYc7js43XC4ge38+Hn5/vcgzRi6hLw3N4o6Vu1s5IeR7EVbASY1h1RNDedRDTE1a0COtQDNGxoSOXHiNWQ2MsFXpK/bid7J3w1nnsiN12HGDSWMt9prEfxYT4OLFY6K9NMwZDX11iiDEIMj4gcOr4iUq0JFO8NkNT/hXEpD6dNSnFxdmTrCye0ckEvtmzu9ZfXS266NS7a0kocoZgR5H87ni8k06Pe+q1qBOAMlyAtZx64CeyOzqmHP9ORSlYeL8fY3PMr8eIyDENrwWf23IQaQCyhjtQ1gHMx4it36wb+EdJTeR20X8lEHybUOwllqAZUDaO7OC0P5xdWEaFDYwFUqOrr5qOnltGAX6ZbCcjX8Dg9kXHqV/sRDj1jgq6/KLCrFp9RM9jim/F+xB0BKLWUERXYohmpo=
  - secure: pfz6K2wKa8/3h0VLmLQv5SBGTe7FkV5mJ6S0kvCmzZZVXKTqGZ3d7GyizGtF+jSmt3lLwyi+gdlGpze+FLevYeJP3qz/8AAFhBo4Hj0w5Lhl7zIMU+zlNFXx2Zd/H81vN0+6y2IrdLx6ZlBnRUZqoJC5HAQhv3z3kWLL6MX70II/L7KgWhXCSc6HgTNzFPJV8abTpKBbJ3Znjnz6peX5645OHLyw/G3U5qQf5nlTwGQQtyPBjxmBuQmeDG44oUtMa+Qh1QFHIgceZeEcx0XK4MtgBnfI9Co+KwSfI1l0sZIXSusZFmAAJ/048i68KTuDr5c8ZYTC9B92QfDew4YIbEkUyNuTzGB3I4rNJXLu5cOWlrqtGJ1G/B9XT6q49Xggfsm45kd+cT5f9hP65VrupdeTfZPpy5MZCYFMFA0i+NjxcOh/fyF2je8qFNgiICL0RDPi4b99PuNEvwwjpic+mFzkwqAR28OxA/tKnGZeonCxcs5xUygczqhMupb3FqgnsAv+Hx5Nwsi8zghbbdX8iW379wqEuGD8T+cTVvGci7qRs8YgM079Q3Dqmo2iCuRb/J+BHLAzxgyV9PdI4746fH2J7pyBYMXEsVKs01OxSOmEC8AbIcVkKz6HXuwbpIZo4TLPInwR8Vflw2yk1T3duCHMSHUl2rSoSHqhuSYIX0k=
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - node_modules
  - bower_components
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
